[build]
  functions = "functions"

[[redirects]]
  to = "/.netlify/functions/api"
  from = "/"
  status = 200

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"

[functions."api"]
  schedule = "@hourly"