[build]
  functions = "functions"

[[redirects]]
  to = "/.netlify/functions/post-valores:splat"
  from = "/api/*"
  status = 200

[[redirects]]
  to = "/.netlify/functions/fetch-cop"
  from = "/cop"
  status = 200

[[redirects]]
  to = "/.netlify/functions/fetch-btc"
  from = "/btc"
  status = 200

[[redirects]]
  to = "/.netlify/functions/fetch-db"
  from = "/db"
  status = 200

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"

[functions.fetch-cop]
schedule = "58 */23 * * *"

[functions.fetch-btc]
schedule = "58 */23 * * *"

[functions.post-valores]
schedule = "59 */23 * * *"